# Generated by Django 4.0 on 2021-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='company',
        ),
    ]
