# Generated by Django 4.0 on 2021-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_company_alter_customuser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('SALES', 'SALES'), ('SUPPORT', 'SUPPORT')], max_length=32),
        ),
    ]
