# Generated by Django 4.0 on 2021-12-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_events', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AddField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_contact_events', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contact_contracts', to='users.customuser'),
        ),
    ]
