# Generated by Django 4.0 on 2021-12-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_contract_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(blank=True),
        ),
    ]
