# Generated by Django 4.0 on 2021-12-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_status_options_alter_event_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
